In [2]:
import requests
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
import re
import xml.etree.ElementTree as ET

In [3]:
def collect_data(cur_page, items_per_page):
    # Khai báo sẵn các mảng để đưa vào dataframe
    name = []
    region = []
    country = []
    overall = []
    AcademicReputation = []
    EmployerReputation = []
    FacultyStudentRatio = []
    CitationsPerFaculty = []
    InternationalFacultyRatio = []
    InternationalStudentsRatio = []
    InternationalResearchNetwork = []
    EmploymentOutcomes = []
    Sustainability = []
    
    url = "https://www.topuniversities.com/rankings/endpoint"

    querystring = {"nid":"3897789","page":f"{cur_page}","items_per_page":f"{items_per_page}","tab":"indicators","region":"","countries":"","cities":"","search":"","star":"","sort_by":"overallscore","order_by":"asc","program_type":""}

    payload = ""
    headers = ""

    # Gửi yêu cầu kết nối
    response = requests.request("GET", url, data=payload, headers=headers, params=querystring)
    
    # Nếu trả về Status 200 --> Success
    if response.status_code == 200:
        text = response.json()
        
        list_uni = text['score_nodes']  

        for i in range(items_per_page):
            # Tên đại học
            name.append(list_uni[i]['title'])

            # Châu lục
            region.append(list_uni[i]['region'])
            
            # Vị trí
            country.append(list_uni[i]['country'])
            
            # Điểm trung bình
            overall.append(list_uni[i]['overall_score'])
            
            # Danh sách điểm chi tiết
            scores = list_uni[i]['scores']
            
            AcademicReputation.append(scores[0]['score'])
            EmployerReputation.append(scores[1]['score'])
            FacultyStudentRatio.append(scores[2]['score'])
            CitationsPerFaculty.append(scores[3]['score'])
            InternationalFacultyRatio.append(scores[4]['score'])
            InternationalStudentsRatio.append(scores[5]['score'])
            InternationalResearchNetwork.append(scores[6]['score'])
            EmploymentOutcomes.append(scores[7]['score'])
            Sustainability.append(scores[8]['score'])
                
    data = pd.DataFrame({
        "Institution Name": name,
        "Region": region,
        "Country": country, 
        "Overall": overall,
        "Academic Reputation": AcademicReputation,
        "Employer Reputation": EmployerReputation,
        "Faculty Student Ratio": FacultyStudentRatio,
        "Citations Per Faculty": CitationsPerFaculty,
        "International Faculty Ratio": InternationalFacultyRatio,
        "International Students Ratio": InternationalStudentsRatio,
        "International Research Network": InternationalResearchNetwork,
        "Employment Outcomes": EmploymentOutcomes,
        "Sustainability": Sustainability,
    })
    
    return data

In [4]:
def Generate_Universities_Dataset(quantity, items_per_page):
    index = 0
    num_uni = 0
    data = pd.DataFrame()
    
    # Nếu số lượng vượt quá yêu cầu thì kết thúc
    while num_uni < quantity:
        data = pd.concat([data, collect_data(index, items_per_page)], ignore_index=True)
        
        num_uni += items_per_page
        index += 1

    return data

In [ ]:
# Lưu data vào file csv
uni_df = Generate_Universities_Dataset(1200, 15)

file_path = './Data/universities.csv'

uni_df.to_csv(file_path, index=False)

print(f'Data saved to {file_path}')

In [6]:
# DataFrame World Universities Ranking
uni_df

,Institution Name,Region,Country,Overall,Academic Reputation,Employer Reputation,Faculty Student Ratio,Citations Per Faculty,International Faculty Ratio,International Students Ratio,International Research Network,Employment Outcomes,Sustainability
0,Massachusetts Institute of Technology (MIT),North America,United States,100,100,100,100,100,100,88.2,94.3,100,95.2
1,University of Cambridge,Europe,United Kingdom,99.2,100,100,100,92.3,100,95.8,99.9,100,97.3
2,University of Oxford,Europe,United Kingdom,98.9,100,100,100,90.6,98.2,98.2,100,100,97.8
3,Harvard University,North America,United States,98.3,100,100,98.3,100,84.6,66.8,100,100,96.7
4,Stanford University,North America,United States,98.1,100,100,100,99.9,99.9,51.2,95.8,100,94.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,Université de Sousse,Africa,Tunisia,n/a,3.7,1.1,60.7,1.7,1.1,2.1,1.2,7.9,1
1196,Université Toulouse - Jean Jaurès,Europe,France,n/a,10.1,2.6,1.2,7,28.5,21.6,12.5,6.7,1.1
1197,Utah State University,North America,United States,n/a,6.6,3.2,6.3,24.4,1.1,1.7,23.8,9.5,15.8
1198,VSB - Technical University of Ostrava,Europe,Czechia,n/a,5.4,10.3,15.5,4.3,8.4,22,1.8,9.4,8.4
1199,Vancouver Island University,North America,Canada,n/a,5,3.3,58,1.1,n/a,n/a,1.1,6.8,n/a